version: '3'
services:
  app:
    image: skanderbelhassen/devopsimage:latest
    ports:
      - "8082:8082"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3307:3306"