pipeline {
    agent any

    stages {
        stage('GIT') {
            steps {
                echo 'Pulling...'
                git branch: 'roukaia',
                url: 'https://github.com/RoukaiaKHELIFI/DevOps_Project.git'
            }
        }

        stage('Maven Build') {
            steps {
                script {
                    def workspace = pwd()
                    dir("${workspace}/DevOps_Project-main/DevOps_Project") {
                        sh 'mvn clean compile'
                    }
                }
            }
        }
    }
}
